### ISSUE TITLE
OneTouch support

### ISSUE THREAD

**Issue by Carlgo11** [authy/authy-wordpress#15]
Hi,

Since Authy released the OneTouch service I'd love to see this being implemented into the wordpress plugin.

**Comment by Carlgo11** [comment]
@danpal @senekis is this something that will be added?

**Comment by jashsayani** [comment]
They have an SDK so this project can be easily forked and tweaked to use OneTouch.

**Comment by tufla** [comment]
Hi, here Henry from Authy team. We will be releasing a new version of WordPress plugin supporting latest platform version and onetouch. This should be happening before the end of current Q1.

**Comment by Carlgo11** [comment]
Hi Henry,
thank you very much for the information.
Looking forward to the release! :smiley:
